### ISSUE TITLE
项目中引用报错 

### ISSUE THREAD

**Issue by zhaojing** [xianmobilelab/weibo_jingzhao#3]
```
dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /Users/**/Library/Developer/CoreSimulator/Devices/15AA3C87-789C-491C-BE6F-38A316B9A0F9/data/Containers/Bundle/Application/284C4AE4-B07B-4605-9FA1-F8F9D32EF0A0/Test.app/Frameworks/libswiftXCTest.dylib
  Reason: image not found
```

1.我只大约看一下不是单元测试就用Linked Frameworks and Libraries ，但是忘了依赖库是单元测试的了

文档：Because unit test targets are missing the “Linked Frameworks and Libraries” section in their “General” settings tab, you must instead drag the built frameworks to the “Link Binaries With Libraries” build phase.

**但是以前经验都可以搜索的到，可以帮我看看关键词哪里搜索错了，谢谢**
- 我先搜素的/libswiftXCTest.dylib  Reason: image not found 搜到的是http://stackoverflow.com/questions/26024100/dyld-library-not-loaded-rpath-libswiftcore-dylib
- dyld: Library not loaded: @rpath/XCTest.framework 这样搜到的不合逻辑
- https://github.com/Carthage/Carthage/issues/756 文档问题里搜到的问题一模一样，答案却是不对的

**Comment by itrufeng** [comment]
@zhaojing 
https://github.com/Carthage/Carthage#if-youre-building-for-os-x

On your application targets’ “General” settings tab, in the `“Embedded Binaries”` section, drag and drop each framework you want to use from the Carthage/Build folder on disk.

注意这里的Embedded Binaries.
但是如果是测试的话，就在测试中link就好了，不需要Embedded.

**Comment by itrufeng** [comment]
@zhaojing 
这个不需要Embedded 是OSX才需要。
